-- MySQL Script generated by MySQL Workbench
-- Rab 18 Nov 2020 02:00:14  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_dashboard
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_dashboard` ;

-- -----------------------------------------------------
-- Schema db_dashboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dashboard` DEFAULT CHARACTER SET utf8 ;
USE `db_dashboard` ;

-- -----------------------------------------------------
-- Table `db_dashboard`.`tipe_pekerja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`tipe_pekerja` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`tipe_pekerja` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dashboard`.`pekerja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`pekerja` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`pekerja` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_employee` INT NOT NULL,
  `tipe_pekerja_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `tipe_pekerja_id`),
  INDEX `fk_pekerja_tipe_pekerja1_idx` (`tipe_pekerja_id` ASC),
  CONSTRAINT `fk_pekerja_tipe_pekerja1`
    FOREIGN KEY (`tipe_pekerja_id`)
    REFERENCES `db_dashboard`.`tipe_pekerja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dashboard`.`pekerjaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`pekerjaan` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`pekerjaan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pemberi_tugas_id` INT UNSIGNED NOT NULL,
  `pekerja_id` INT UNSIGNED NOT NULL,
  `nama` VARCHAR(45) NOT NULL,
  `status` ENUM("approve", "revisi", "review") NOT NULL,
  PRIMARY KEY (`id`, `pemberi_tugas_id`, `pekerja_id`),
  INDEX `fk_pekerjaan_pekerja1_idx` (`pemberi_tugas_id` ASC),
  INDEX `fk_pekerjaan_pekerja2_idx` (`pekerja_id` ASC),
  CONSTRAINT `fk_pekerjaan_pekerja1`
    FOREIGN KEY (`pemberi_tugas_id`)
    REFERENCES `db_dashboard`.`pekerja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pekerjaan_pekerja2`
    FOREIGN KEY (`pekerja_id`)
    REFERENCES `db_dashboard`.`pekerja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dashboard`.`hasil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`hasil` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`hasil` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pekerjaan_id` INT UNSIGNED NOT NULL,
  `pekerja_id` INT UNSIGNED NOT NULL,
  `path_file` TEXT NOT NULL,
  PRIMARY KEY (`id`, `pekerjaan_id`, `pekerja_id`),
  INDEX `fk_hasil_pekerjaan1_idx` (`pekerjaan_id` ASC),
  INDEX `fk_hasil_pekerja1_idx` (`pekerja_id` ASC),
  CONSTRAINT `fk_hasil_pekerjaan1`
    FOREIGN KEY (`pekerjaan_id`)
    REFERENCES `db_dashboard`.`pekerjaan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hasil_pekerja1`
    FOREIGN KEY (`pekerja_id`)
    REFERENCES `db_dashboard`.`pekerja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dashboard`.`document`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`document` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`document` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pekerjaan_id` INT UNSIGNED NOT NULL,
  `pekerja_id` INT UNSIGNED NOT NULL,
  `path_file` TEXT NOT NULL,
  PRIMARY KEY (`id`, `pekerjaan_id`, `pekerja_id`),
  INDEX `fk_document_pekerjaan1_idx` (`pekerjaan_id` ASC),
  INDEX `fk_document_pekerja1_idx` (`pekerja_id` ASC),
  CONSTRAINT `fk_document_pekerjaan1`
    FOREIGN KEY (`pekerjaan_id`)
    REFERENCES `db_dashboard`.`pekerjaan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_pekerja1`
    FOREIGN KEY (`pekerja_id`)
    REFERENCES `db_dashboard`.`pekerja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `db_dashboard`.`tipe_pekerja`
-- -----------------------------------------------------
START TRANSACTION;
USE `db_dashboard`;
INSERT INTO `db_dashboard`.`tipe_pekerja` (`id`, `nama`) VALUES (1, 'admin');
INSERT INTO `db_dashboard`.`tipe_pekerja` (`id`, `nama`) VALUES (2, 'pemberi tugas');
INSERT INTO `db_dashboard`.`tipe_pekerja` (`id`, `nama`) VALUES (3, 'pekerja');

COMMIT;

