-- MySQL Script generated by MySQL Workbench
-- Rab 17 Feb 2021 09:27:36  WIB
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_dashboard
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_dashboard` ;

-- -----------------------------------------------------
-- Schema db_dashboard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dashboard` DEFAULT CHARACTER SET utf8 ;
USE `db_dashboard` ;

-- -----------------------------------------------------
-- Table `db_dashboard`.`pekerjaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`pekerjaan` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`pekerjaan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dashboard`.`pekerja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`pekerja` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`pekerja` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_employee` INT NOT NULL,
  `nama_pekerja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dashboard`.`aset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`aset` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`aset` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pekerjaan_id` INT UNSIGNED NOT NULL,
  `path_file` TEXT NOT NULL,
  `is_hasil` ENUM('HASIL', 'DOKUMEN', 'REVIEW') NOT NULL,
  PRIMARY KEY (`id`, `pekerjaan_id`),
  INDEX `fk_document_pekerjaan1_idx` (`pekerjaan_id` ASC),
  CONSTRAINT `fk_document_pekerjaan1`
    FOREIGN KEY (`pekerjaan_id`)
    REFERENCES `db_dashboard`.`pekerjaan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dashboard`.`pekerja_pekerjaan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`pekerja_pekerjaan` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`pekerja_pekerjaan` (
  `pekerjaan_id` INT UNSIGNED NOT NULL,
  `pekerja_id` INT UNSIGNED NOT NULL,
  `position` ENUM('pekerja', 'pembantu', 'petugas', 'review') NOT NULL,
  PRIMARY KEY (`pekerjaan_id`, `pekerja_id`),
  INDEX `fk_pekerjaan_has_pekerja_pekerja1_idx` (`pekerja_id` ASC),
  INDEX `fk_pekerjaan_has_pekerja_pekerjaan1_idx` (`pekerjaan_id` ASC),
  CONSTRAINT `fk_pekerjaan_has_pekerja_pekerjaan1`
    FOREIGN KEY (`pekerjaan_id`)
    REFERENCES `db_dashboard`.`pekerjaan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pekerjaan_has_pekerja_pekerja1`
    FOREIGN KEY (`pekerja_id`)
    REFERENCES `db_dashboard`.`pekerja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dashboard`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_dashboard`.`status` ;

CREATE TABLE IF NOT EXISTS `db_dashboard`.`status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pekerjaan_id` INT UNSIGNED NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `type` ENUM('available', 'started', 'approved', 'amend', 'review') NOT NULL,
  `due_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `pekerjaan_id`),
  INDEX `fk_status_pekerjaan1_idx` (`pekerjaan_id` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
